baseURL = 'https://rajeshkhadka.com/'
languageCode = 'en-us'
title = 'Rajesh Khadka'
theme = 'hugo-ink'
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
subtitle = "Software Engineer (Backend, Data Science, Machine Learning)"

# Optional 64x64 avatar image.
avatar = "https://media-exp1.licdn.com/dms/image/C5603AQFCMJoD3L8qtQ/profile-displayphoto-shrink_800_800/0/1647364546593?e=1653523200&v=beta&t=c_hXUH3ddhBFRcTXquj3iAPTbuk9DSs-Tkw2oYjVaaI"

# Content types to disable Disqus on.
disableDisqusTypes = ["page"]

featherIconsCDN = true

mode = "dark" # "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/khadkarajesh"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/rajeshkhadka/"

[taxonomies]
tag = "tags"